site_name: Momento
theme:
    name: readthedocs
    logo: assets/logo.png
extra_css:
    - assets/style.css
extra_javascript:
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
docs_dir: src
site_dir: site
plugins:
    - search
    - autorefs
    - mkdocs-jupyter:
          include_source: true
          execute: false
          allow_errors: false
    - mkdocstrings:
          handlers:
              python:
                  paths:
                      - ..
                  options:
                      show_submodules: true
                      docstring_style: google
                      separate_signature: true
                      members_order: source
                      filters: ["!^_"]
    - plantuml:
          puml_url: https://www.plantuml.com/plantuml/
          theme:
              enabled: false
markdown_extensions:
    - pymdownx.arithmatex:
          generic: true
    - pymdownx.snippets:
          base_path: ../..
          check_paths: false
nav:
    - Overview: index.md
    - Python Backend:
          - Architecture:
                - Overview: api/architecture.md
                - WebSocket Endpoints: api/websocket_endpoints.md
                - AI Models: api/models.md
                - Core Services: api/services.md
                - Readme: api/readme_link.md
                - Reference (PY): api/py.md
    - Web Frontend:
          - Architecture:
                - Overview: web/architecture.md
                - Communication: web/communication.md
                - Testing: web/testing.md
                - Reference (TS): web/ts/globals.md
    - Evaluation:
          - Architecture:
                - Overview: evaluation/architecture.md
                - Data Loading: evaluation/data_loading.md
                - Configuration: evaluation/configuration.md
                - Baselines: evaluation/baselines.md
                - Datasets: evaluation/datasets.md
                - Metrics: evaluation/metrics.md
          - Analysis:
                - MS MARCO Passage v1: evaluation/analysis/evaluation_ms_marco_passage.ipynb
                - MS MARCO QnA: evaluation/analysis/evaluation_ms_marco_qna.ipynb
                - OpenLifelogQA: evaluation/analysis/evaluation_openlifelog_qa.ipynb
                - TimelineQA (sparse): evaluation/analysis/evaluation_timeline_qa_sparse.ipynb
                - TimelineQA (medium): evaluation/analysis/evaluation_timeline_qa_medium.ipynb
                - TimelineQA (dense): evaluation/analysis/evaluation_timeline_qa_dense.ipynb
          - Reference (PY): evaluation/py.md
    - READMEs:
          - Project Overview (root README): readme_link.md
          - API (Python Backend): api/readme_link.md
          - Web Frontend: web/readme_link.md
          - Communication (Protobuf): protos/readme_link.md
          - Evaluation: evaluation/readme_link.md
